# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Routes
spring.cloud.gateway.routes[0].id=user-management
spring.cloud.gateway.routes[0].uri=lb://USER-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=project-management
spring.cloud.gateway.routes[1].uri=lb://PROJECT-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[1].predicates[0]=Path=/projects/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false
