# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Routes
spring.cloud.gateway.routes[0].id=user-management
spring.cloud.gateway.routes[0].uri=lb://USER-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=project-management
spring.cloud.gateway.routes[1].uri=lb://PROJECT-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[1].predicates[0]=Path=/projects/**

spring.cloud.gateway.routes[2].id=student-management
spring.cloud.gateway.routes[2].uri=lb://STUDENT-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[2].predicates[0]=Path=/students/**

spring.cloud.gateway.routes[3].id=address-management
spring.cloud.gateway.routes[3].uri=lb://ADDRESS-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/addresses/**

spring.cloud.gateway.routes[4].id=location-management
spring.cloud.gateway.routes[4].uri=lb://LOCATION-MANAGEMENT-SYSTEM
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/locations/**
