# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Routes
spring.cloud.gateway.routes[0].id=user-management-system
spring.cloud.gateway.routes[0].uri=lb://user-management-system
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=course-management-system
spring.cloud.gateway.routes[1].uri=lb://course-management-system
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**

spring.cloud.gateway.routes[2].id=student-management-system
spring.cloud.gateway.routes[2].uri=lb://student-management-system
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/students/**

spring.cloud.gateway.routes[3].id=department-management-system
spring.cloud.gateway.routes[3].uri=lb://department-management-system
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/departments/**

spring.cloud.gateway.routes[4].id=college-management-system
spring.cloud.gateway.routes[4].uri=lb://college-management-system
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/colleges/**

spring.cloud.gateway.routes[5].id=university-management-system
spring.cloud.gateway.routes[5].uri=lb://university-management-system
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/universities/**

spring.cloud.gateway.routes[6].id=enrollment-management-system
spring.cloud.gateway.routes[6].uri=lb://enrollment-management-system
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/enrollments/**

spring.cloud.gateway.routes[7].id=project-management-system
spring.cloud.gateway.routes[7].uri=lb://project-management-system
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/projects/**

spring.cloud.gateway.routes[8].id=branch-management-system
spring.cloud.gateway.routes[8].uri=lb://branch-management-system
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/branches/**

spring.cloud.gateway.routes[9].id=company-management-system
spring.cloud.gateway.routes[9].uri=lb://company-management-system
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/companies/**

spring.cloud.gateway.routes[10].id=employee-management-system
spring.cloud.gateway.routes[10].uri=lb://employee-management-system
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/employees/**

# Actuator
management.endpoints.web.exposure.include=health,info
